### ISSUE TITLE
How to setup the teradata driver?

### ISSUE THREAD

**Issue by pberden** [dbfit/dbfit-teradata#1]
Hi,

I know nothing about java or jar's, so this question might sound stupid... But how do I setup the teradata driver in DbFit? This is what I've done:
- Download and unzipped dbfit-complete-2.0.0-rc5
- Copied and replaced the contents of AcceptanceTests of your git to the FitNesseRoot/DbFit

However I don't know what to do with dbfit folder?

**Comment by MMatten** [comment]
This was actually built for dbft 1.1 and works fine with that version.

I haven't had time to upgrade it yet for dbfit 2.0.

I'm hoping to get it done in the next couple of months.

If you like I can give you a 1.1 installation to use.

**Comment by pberden** [comment]
That would be great! Can you email the 1.1. installation to paulberden and then gmail.com?

**Comment by MMatten** [comment]
I've added a binary ZIP distribution for you. Just grab it from the git repo now.

**Comment by pberden** [comment]
Thanks I'll give a try tomorrow!
