### ISSUE TITLE
Could not find fixture

### ISSUE THREAD

**Issue by pberden** [dbfit/dbfit-teradata#2]
Hi, I unzipped and started fitnesse. I've added: 
!path lib/*.jar
to the HelloWorld page.

Then created the SetUp page as a child.
And a FirstTest also as a child of HelloWorld. It then throws this error:

 Set Up: .HelloWorld.SetUp (edit)
dbfit.TeradataTest
Could not find fixture: dbfit.TeradataTest.

Connect
Could not find fixture: Connect.    192.168.44.212  XXX XXX XXX
Ordered Query
Could not find fixture: OrderedQuery.    SELECT OBJECT_ID FROM PBE_SEM.MDQR_OBJECT
OBJECT_ID
x

Is there something I've missed?

**Comment by MMatten** [comment]
Try adding an 

|Import|
 |dbfit.fixtures| 

Also have a look at the Teradata acceptance tests. 

Mark

**Comment by MMatten** [comment]
Try creating a single page Hello World first, with no setup or teardown.

**Comment by pberden** [comment]
Hi, thanks for your help so far!

I've created a simple HelloWorld page with:

!path lib/*jar

|Import|
|dbfit.fixtures|

!|dbfit.TeradataTest|
|Connect|IP|USER|PASS|PBE_SEM|

!|Query| select 'test' as x from dual|
|x|
|test|

But still I get a "Could not find fixture" error.

Isn't there anything more I need to do for the teradata connectivity? How does DbFit talk to the database? With jdbc for example? Is that included in the zip?

Regards,

Paul

**Comment by MMatten** [comment]
I think I'd better check the zip file!

I have not included the JDBC driver JARs. You'll need to incluse terajdbc.jar and tdgssconfig.jar from the drivers from the Teradata download.

**Comment by MMatten** [comment]
I've totally messed up the dbfit JAR file!

I'll work on adding the correct one now!

**Comment by MMatten** [comment]
I'd overwritten the dbfit JAR file. Corrected now. Please try again!

**Comment by pberden** [comment]
Great, It works! Thanks for your help, if you need any help with testing in the future let me know.
