### ISSUE TITLE
DBFit Password Encryption not working

### ISSUE THREAD

**Issue by jwusch** [dbfit/dbfit-teradata#3]
Hi, I am using the encrypt.sh command in the Fitnesse root to encrypt my human readable passwords, it looks like your version of the TeraData harness doesn't handle it, as it just passes the ENC(XXXXXX) string as password instead of attempting a decrypt.

**Comment by MMatten** [comment]
This is currently a dbfit 1.1 implementation. I think password encryption was added in dbfit 2.0RC4.

I'll be working with Jake shortly reintegrate this into dbfit 2.0.
