### ISSUE TITLE
German characters

### ISSUE THREAD

**Issue by pberden** [dbfit/dbfit-teradata#4]
Hi, I'm trying to validate strings of text with "special" characters in it. See screenshot:
![screenshot](https://f.cloud.github.com/assets/3209733/1332009/9d9ea45a-356e-11e3-9f0a-ce28df755987.png)

My guess is that this can be solved by setting another character set. If so, how can I do that?

**Comment by MMatten** [comment]
There seems to be some translation happening somewhere.

I don't know where.

Can you get a hex dump of what gets inserted into the database?

**Comment by pberden** [comment]
Hi MMatten, I don't know how to create a hex dump of the inserted fields.

I've inserted the data with a ODBC connection with character set UTF-8. In the teradata studio, the data shows as in the first row in the screenshot which is correct. So my guess is that when querying the database something goes wrong. Which character set does the connection use by default? If this is ASCII, then that will be the problem. If so, is there a way to set the character-set of the jdbc connector?

**Comment by MMatten** [comment]
Take a look at the available JDBC connection properties. It might be settable via the URL. If so, we might be able to 'shoe horn' it into the existing Connect fixture params. If not, a code change will be required...

**Comment by pberden** [comment]
I found this link: http://developer.teradata.com/doc/connectivity/jdbc/reference/current/jdbcug_chapter_2.html#BABJIHBJ

It seems that setting charset via the URL is possible. Where can I find this URL in the DbFit package?

**Comment by MMatten** [comment]
So the CHARSET=UTF8 property, specified in the connection URL should do it.

One adds connection properties to the URL using 

/<key>=<value>

E.g. 

jdbc:teradata://<DatabaseServerName>/CHARSET=UTF8

If you use the full connection string version of the dbfit Connect fixture you can put this on the end of your URL. See:

http://benilovj.github.io/dbfit/docs/reference.html

You can put the URL on the page or use the "Connect Using File" version of the fixture and put the URL in the file along with the user name and pass word.

**Comment by pberden** [comment]
Thank you very, very, very much again! I got the test working with UTF-8!!!

The full connection string is now:

!|dbfit.TeradataTest|
|Connect|jdbc:teradata://DatabaseServerName/USER=XYZ,PASSWORD=XYZ,DATABASE=XYZ,CHARSET=UTF8|

**Comment by MMatten** [comment]
Great!

I like to put the connect details into files so that the tests become independent of the environment.
