### ISSUE TITLE
DbFit 2.1

### ISSUE THREAD

**Issue by pberden** [dbfit/dbfit-teradata#6]
Hi MMatten,

Have you had time to upgrade the dbfit-teradata to version 2? If I can be of any help, let me know! I probably have some time available the coming weeks... 

Regards, Paul

**Comment by MMatten** [comment]
Hi Paul,

I'm afraid not. My life is still pretty crazy at the moment!

You might have noticed that dbfit-teradata has moved closer to the main dbfit, if not in terms of code, then in terms of ownership, as I've transferred the project to the dbfit organisation on github. So, Jake and Javor also now have better visibility of it.

If you have some time it might be worth you dropping them a note to see if they're intending on doing any work to merge the projects, or perhaps try it yourself.

Have you taken a look at the code from either project yet? They should be fairly easy to get opened up in Eclipse and compiled. I can help if you're having problems building the Teradata project.

**Comment by pberden** [comment]
Hi, I see that dbfit-teradata has moved to the dbfit organization. That's a good thing! I noticed the issue 168 where someone else had the same request as I, and all developer were currently busy. So it probably wouldn't make much sense to ask again.

I will try to open the project in Eclipse and see if I can compile it. Are you fine with me contacting you via GitHub in case I get stuck?

**Comment by MMatten** [comment]
Teradata support has been added to the main DbFit codebase.
