### ISSUE TITLE
 Could not find fixture: dbfit.TeradataTest.

### ISSUE THREAD

**Issue by samiulanik** [dbfit/dbfit-teradata#7]
I am having problem with dbfit with teradata. I have tried following in the HelloWorld page

```
!path C:\Users\xxxx\Downloads\dbfit-complete-3.2.0\lib
|Import|
|dbfit.fixtures|
!|dbfit.TeradataTest|
!|Connect|jdbc:teradata://IP_Address /USER=U,PASSWORD=p,DATABASE=db_name,TMODE=ANSI,CHARSET=ASCII|
```

When I try to run I get  Could not find fixture: dbfit.TeradataTest. and  Could not find fixture: Connect. error.
I am using Teradata jdbc driver 15.10 (Also tried 15.00). Both terajdbc4.jar and tdgssconfig.jar are copied in the lib folder mentioned in the path.

**Comment by MMatten** [comment]
Hi. This source repository is implemented Teradata support based on an old version of DbFit (v1.1).

Teradata support has now been added to the main DbFit codebase.

Please use the releases from the main codebase.
